export enum Genre {
  Nouvelle = 'Nouvelle',
  Conte = 'Conte',
  Mythe = 'Mythe',
  Legende = 'Legende',
  Biographie = 'Biographie',
  Autobiographie = 'Autobiographie',
  Chronique = 'Chronique',
  Apologue = 'Apologue',
  Journal = 'Journal',
  Roman = 'Roman',
  Chanson = 'Chanson',
  Elegie = 'Elegie',
  Epopée = 'Epopée',
  Tragéie = 'Tragédie',
  Comédie = 'Comédie',
  Drame = 'Drame',
  Essai = 'Essai',
  Fable = 'Fable',
  Pamphlet = 'Pamphlet',
  Autres = 'Autres',
}