export enum Genre {
  Action = 'Action',
  Autres = 'Autres',
  Aventure = 'Aventure',
  Anticipation = 'Anticipation',
  Autobiographique = 'Autobiographique',
  Biographique = 'Biographique',
  Catastrophe = 'Catastrophe',
  Comédie = 'Comédie',
  Documentaire = 'Documentaire',
  Drame = 'Drame',
  Experimental = 'Experimental',
  Fantastique = 'Fantastique',
  Historique = 'Historique',
  Fantasy = 'Fantasy',
  Horreur = 'Horreur',
  Peplum = 'Peplum',
  Romantique = 'Romantique',
  Science_Fiction = 'Science_Fiction',
  Thriller = 'Thriller',
  Western = 'Western',
}
